# -*- coding: utf-8 -*-
"""python_refresher_april.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BnMkKrx_Lo1Am1CBMQDBPKbHqD41RFyL
"""

print('Hello World')

